### ISSUE TITLE
nerd fonts support?

### ISSUE THREAD

**Issue by thenameofallnames-ig** [molarmanful/kirsch#1]
just an idea, but it would be cool if the font got patched to work with nerd fonts by default.

**Comment by molarmanful** [comment]
Hi, thanks for the suggestion! Please let me know if the Nerd Fonts built in [this prerelease](https://github.com/molarmanful/kirsch/releases/tag/v0.0.2-0) work; if so, then I'll go ahead and release a patch to finalize it.

*As a side note, I'm using WezTerm which allows me to specify fallback fonts. Since I'm not a fan of the patched Nerd Font glyph sizes, I use the complete Nerd Font Symbols as a fallback font to scale the glyphs to my liking. If the patched glyph sizes aren't to your liking, this may be another approach to try.*

**Comment by thenameofallnames-ig** [comment]
well, it seems to work!
![Schermata_20240331_005652](https://github.com/molarmanful/kirsch/assets/19878015/55dd064e-4482-4264-ad1f-7ca03951a12f)
but i do find that the spacing (?) on konsole being a little weird with yay?
![Schermata_20240331_005719](https://github.com/molarmanful/kirsch/assets/19878015/90a7dac2-519e-4e9f-8f15-81ed088809f0)

**Comment by molarmanful** [comment]
Great, glad to see it!
